# Generated by Django 6.0.7 on 2026-07-23 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'sticker categories',
                'db_table': 'sticker_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='stickers/')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Optional search keywords, e.g. ["bear","teddy","cute"]')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='stickers.stickercategory')),
            ],
            options={
                'db_table': 'stickers',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='stickers_categor_aa0cd6_idx')],
            },
        ),
    ]
